# Generated by Django 2.2.15 on 2020-09-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnets', '0003_link_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='ordering',
        ),
    ]
